spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vng
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
